apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    app: {{ .Chart.Name }}
data:
  mongodb-url: {{ .Values.env.MONGODB_URL | b64enc | quote }}
  discord-bot-token: {{ .Values.env.DISCORD_BOT_TOKEN | b64enc | quote }}